# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-functions-weather-api
metadata:
  template: azure-functions-weather-api@0.0.1-beta

services:
  weather-api:
    project: ./src
    language: dotnet
    host: function

infra:
  path: ./infra
  provider: bicep
  module: main

hooks:
  postprovision:
    windows:
      shell: pwsh
      run: |
        $keyVaultName = azd env get-values | Select-String "AZURE_KEY_VAULT_NAME" | ForEach-Object { ($_ -split '=')[1].Trim('"') }
        if ([string]::IsNullOrWhiteSpace($keyVaultName)) {
          Write-Warning "AZURE_KEY_VAULT_NAME not found in azd environment"
          exit 0
        }
        ./scripts/Set-KeyVaultSecrets.ps1 -KeyVaultName $keyVaultName -EnvFilePath ".env"
      continueOnError: false
    posix:
      shell: sh
      run: |
        KEY_VAULT_NAME=$(azd env get-values | grep AZURE_KEY_VAULT_NAME | cut -d'=' -f2 | tr -d '"')
        if [ -z "$KEY_VAULT_NAME" ]; then
          echo "Warning: AZURE_KEY_VAULT_NAME not found"
          exit 0
        fi
        pwsh ./scripts/Set-KeyVaultSecrets.ps1 -KeyVaultName "$KEY_VAULT_NAME" -EnvFilePath ".env"
      continueOnError: false

pipeline:
  provider: github
